### ISSUE TITLE
Crash on publish to YouTube, plus log includes failure to attach Facebook credentials

### ISSUE THREAD

**Issue by baghdadbrian** [StoryMaker/storymaker#167]
[bugreport.txt](https://github.com/StoryMaker/storymaker/files/407399/bugreport.txt)

**Comment by n8fr8** [comment]
"31 E AndroidRuntime: FATAL EXCEPTION: main
08-08 09:25:49.086 29631 29631 E AndroidRuntime: Process: org.storymaker.app, PID: 29631
08-08 09:25:49.086 29631 29631 E AndroidRuntime: java.lang.NoClassDefFoundError: com.google.api.client.http.javanet.NetHttpTransport
08-08 09:25:49.086 29631 29631 E AndroidRuntime: 	at io.scal.secureshare.controller.YoutubeSiteController.<init>(YoutubeSiteController.java:51)
08-08 09:25:49.086 29631 29631 E AndroidRuntime: 	at io.scal.secureshare.controller.SiteController.getSiteController(SiteController.java:109)"

is a key bit. Seems like we are missing the google http libraries.

**Comment by n8fr8** [comment]
Found this as well:

08-08 09:26:06.186  2858  3360 E Parcel  : Class not found when unmarshalling: scal.io.liger.model.FullMetadata
08-08 09:26:06.186  2858  3360 E Parcel  : java.lang.ClassNotFoundException: scal.io.liger.model.FullMetadata
08-08 09:26:06.186  2858  3360 E Parcel  : 	at java.lang.Class.classForName(Native Method)
08-08 09:26:06.186  2858  3360 E Parcel  : 	at java.lang.Class.forName(Class.java:251)
08-08 09:26:06.186  2858  3360 E Parcel  : 	at java.lang.Class.forName(Class.java:216)
08-08 09:26:06.186  2858  3360 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Par

**Comment by n8fr8** [comment]
This like a missing API key issue perhaps:

2 E AndroidRuntime: Caused by: java.lang.NullPointerException
08-08 09:28:49.091 30582 30582 E AndroidRuntime: 	at io.scal.secureshare.login.FacebookLoginActivity.onStop(FacebookLoginActivity.java:107)
08-08 09:28:49.091 30582 30582 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1218)
08-08 09:28:49.091 30582 30582 E AndroidRuntime: 	at android.app.Activity.performStop(Activity.java:5596)
08-08 09:28:49.091 30582 30582 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3772)
08-08 09:28:49.091 30582 30582 E AndroidRuntime: 	... 11 more
